eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/fanxl12/config-repo
          username: 744822514@qq.com
          password: fxl421125
  rabbitmq:
    host: 192.168.99.100

management:
  endpoints:
    web:
      exposure:
        include: "*"