eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka/

spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/fanxl12/config-repo
          username: 744822514@qq.com
          password: fxl421125
          basedir: C:/WorkSpace/JavaSpace/config/basedir
  rabbitmq:
    host: rabbitmq

management:
  endpoints:
    web:
      exposure:
        include: "*"